### ISSUE TITLE
create pasta without finding an ID with select to prevent races

### ISSUE THREAD

**Issue by starius** [starius/pasta#3]

**Comment by sergeevabc** [comment]
Could you be so kind to tell what is “Secure ID” and what is expected shelf life of uploaded pastes/files?

**Comment by starius** [comment]
Secure ID means that file gets long random ID (16 bytes of entropy). If you don't check, it will get mnemonic ID (one or more English words, easy to remember or type on another device, but also easy to guess).

**Comment by sergeevabc** [comment]
@starius, and what about the second part of the question, namely the expiration time of uploaded pastes/files?
