### ISSUE TITLE
Better documentation for self-hosting

### ISSUE THREAD

**Issue by Rycoh99** [starius/pasta#6]
Hello! I have been using the official instance for quite some time and I can say this is my favorite pastebin-like service, but the only thing that I don't get is the self-hosting part, I would love to self-host this for my own needs, but the command from the landing page ("go get github.com/starius/pasta/gopasta") is deprecated in newer Go versions, and step 4 from the GitHub README is not explained in depth. I can't seem to figure it out 😢

**Comment by starius** [comment]
Hi! I'm happy to hear from you!
The site is now on new domain https://pastacity.nl

To download the code and build the binary, use the following command:
```
$ go install github.com/starius/pasta/gopasta@latest
```

It will put the binary to `$GOPATH/bin` directory, which is in most setups in `~/go/bin`.

The binary is self-contained, so if needed you can move it to another machine with the same OS and CPU architecture and run there.

To run the binary:

```
./gopasta \
  -cache-bytes 0 -cache-records 0 \
  -allow-files -files-burn \
  -dir /path/to/directory/with/state \
  -listen 127.0.0.1:8042 \
  -max-size 104857600 \
  -domains pastacity.nl,trebzwp2nyrsq6urxkeif7iz5vpf3ppnlzvy6xdxwomgebx2vpczzsqd.onion \
  -letsencrypt-domains pastacf.com,www.pastacf.com,pastacity.nl,www.pastacity.nl
```

Replace `-dir`, `-domains` and ` -letsencrypt-domains` with your values. `-domains` is the list to show in the bottom of main page. `-letsencrypt-domains` is the list of allowed domains to issue letsencrypt cert for it automatically.

The binary needs to bind 443 and 80 TCP ports on the server to run HTTP server, so run as root or run the following command to allow the binary to bind ports below 1024:
```
sudo apt-get install libcap2-bin
sudo setcap 'cap_net_bind_service=+ep' /path/to/gopasta
```

I will update the instructions later.

**Comment by starius** [comment]
I updated the docs here: https://github.com/starius/pasta/tree/master/gopasta
and removed `go get` command from the site itself.
Please open new issue, if you have more quiestions.
